apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-DaemonSet
  labels:
    app: ds
spec:
  selector:
    matchLabels:
      app: ds
  template:
    metadata:  
      labels: 
        app: ds
    spec:
      containers:
        - name: my-ds-container
          image: nginx:latest
          ports:
          - name: nginx-port
            containerPort: 80