apiVersion: app/v1
kind: DaemonSet
metadata:
  name: my-daemon
  labels:
    app: daemon
spec:
  selector:
    matchLables:
      app: daemon
  template:
    metadata:
      labels:
        app: daemon
    spec:
      containers:
        - name: daemon-container
          image: nginx:latest
          ports:
            -containerPort: 80     