apiVersion: v1
kind: Pod
metadata:
  name: my-lbpod
  labels:
    app: lb
spec:
  containers:
  - name: Apache-tomcat-container
    image: httpd:latest
    ports:
      -name: httpd-port
        containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-svc
  labels:
    app: lb
spec:
  type: LoadBalancer
  selector:
    app: lb
    ports:
    - name: httpd-svc-port
      protocol: TCP
      port: 80
      targetPort: 80