apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
      name: rs-template
      labels:
        app: rs
    containers:
      - name: rs-container
        image: nginx:latest
        ports:
        - name: nginx-port
          containerPort: 80